#! /bin/bash
if [[ -z $1 ]]; then
    exit;

elif [[ $1 == "clean" ]]; then
    for file in `ls`; do
        ext=${file##*.}       
        if [ "$ext" == "tex" ] || [ "$ext" == "pdf" ] || [ "$ext" == "tsf" ]; then
            echo "not deleting $file"
        else
            rm $file
        fi
    done;
    exit;
else
    base=${1%.*}
    line=$(head -n 1 ${base}.tex)
    if [[ "$line" == "%tex-main" ]]; then
        echo $base
        pdflatex $base
        bibtex $base
        pdflatex $base 
        pdflatex $base 
        open ${base}.pdf
        exit;
    else
        echo "Not the correct file, you will have a bad time" 
        exit;
    fi
fi
echo "usage maketex <SOURCEtexfile|clean>"
echo "clean will clean up your aux files " 

