#!/bin/bash


function explore_path() {
  #echo "explore  path"
  #echo $1
  local mypath=$(readlink -f ${1})
  local mysuper=$(dirname ${mypath})
  #echo "I check ${mypath}"
  for mycheck in $(ls -A --color=never ${mypath}); do
    #check this dir
    #echo "searching ${mycheck}"
    case $mycheck in
      ".bin")
        #gotem
        #echo "exp1-1"
        #echo "${mypath}/.bin"
        finalie $mode "${mypath}/.bin"
        return $?
        ;;
      "node_modules")
        #meh close enough
        #echo "exp1-2"
        #echo "${mypath}/${mycheck}/.bin"
        finalie $mode "${mypath}/${mycheck}/.bin"
        return $?
        ;;
      *)
        if [[ -d "${mypath}/${mycheck}"  ]]; then
          #one dire wiggle room
          for path in $(ls --color=never -A ${mypath}/${mycheck}) ; do
            local childpath=$(readlink -f ${mypath}/${mycheck}/${path})
            for childcheck in $(ls -A --color=never ${childpath}) ; do
              case $childcheck in
                ".bin")
                  #gotem
                  #echo "exp2-1"
                  #echo "${childpath}/.bin"
                  finalie $mode "${childpath}/.bin"
                  return $?
                  ;;
                "node_modules")
                  #meh close enough
                  #echo "exp2-2"
                  #echo "${childpath}"
                  #echo "${childcheck}/.bin"
                  finalie $mode "${childpath}/${childcheck}/.bin"
                  return $?
                  ;;
              esac
            done
          done
        fi
        ;;
    esac
  done
  return 1
}

#comments
function revsearch() {
  local bot=${1}
  local working=${bot}
  while true ; do
    working="${working}/.."
    reald=$(readlink -f ${working})
    if [[ "${read}" == "${HOME}" || "${reald}" == "/" ]]; then
      return 1
    else
      for thing in $(ls --color=never -A $reald); do
        if [[ "${thing}" == ".bin" ]]; then
          #echo "rev-1"
          #echo "${reald}/${thing}"
          finalie $mode "${reald}/${thing}"
          return $?
        else
          if [[ "${thing}" == "node_modules" ]]; then
            #echo "rev-2"
            #echo "${reald}/${thing}/.bin"
            finalie $mode "${reald}/${thing}/.bin"
            return $?
          fi
        fi
      done
    fi
  done
  return 1
}

function finalie() {
  #echo "finalie"
  #echo $1
  #echo $2
  if [ $1 -eq 0 ]
  then
    #echo "here"
    [[ -n ${2} ]] && export PATH=$2:$PATH && export NODE_JS_ENV="yes"
    return $?
  else
    if [ $1 -lt 0 ]
    then
      [[ -n ${2} ]] && export PATH=${PATH//${2}:/} 
      unset NODE_JS_ENV
      return $?
    fi
  fi
  return 1
}

[[ -n $2 ]]
check=999
if [[ $1 == "off" ]]; then
  mode=-1
  if [[ -n ${2} ]]; then
    args=${2}
  else 
    args="."
  fi
else
  if [[ -n $NODE_JS_ENV ]]; then 
    mode=-1
  else
    mode=0
  fi
  if [[ ${1} != "on" ]]; then
    if [[ -z $1  ]]; then
      args="."
    else
      args=${1}
    fi
  else
    if [[ -n ${2} ]]; then
      args=${2}
    else
      arge="."
    fi
  fi
fi

if [[ -n ${args} ]]; then
  #echo ${args}
  explore_path ${args}
  check=$?
fi

if [[ $check != 0  ]]; then
  revsearch ${PWD}
  check=$?
fi

if [[ $check != 0 ]]; then 
  echo "Failed"
  echo $PATH
  return -1
else
  echo "Success"
  echo $PATH
  return 0
fi


