#! /bin/bash

case `uname` in 
    'Linux'*)
        if [ "${1#*.}" == "rjs.html" ]; then
            chromium --app="file://$PWD/$1"
        else
            xdg-open $1 &> /dev/null
        fi;
        ;;
    'Darwin'*)
        open "$*"
        ;;
esac
        

