#! /bin/bash

case `uname` in 
    'Linux'*)
        if [ "$1" == "index.html" ]; then
            chromium --app="file://$PWD/index.html"
        else
            xdg-open $1 &> /dev/null
        fi;
        ;;
    'Darwin'*)
        open "$*"
        ;;
esac
        

