#! /bin/bash


function detect {
  local asshPid=$(pgrep autossh)
  if [[ $asshPid -gt 0 ]]; then
    return -1
  else
    return 0
  fi
}

function run {
  local servPort=1033
  local localPort=9999
  local proxyAddr='cerebro.chem.vt.edu'
  local logPort=20000
  echo "Starting SOCKS tunnel"
  autossh -M ${logPort} -f -N ${proxyAddr} -p ${servPort} -D ${localPort};


}

function report_active {
  echo "proxy already active"
  echo "to kill use :"
  echo " "
  echo " "
  echo " "
  echo "kill -s SIGTERM $(pgrep autossh)"
}

detect && run || report_active
